### ISSUE TITLE
crash : modifying an item... null pointer

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#26]
Release : 0.8
Occurence : always
Tablet only (seen on Nexus 7 Android 6)

java.lang.NullPointerException: Attempt to read from field 'long java.util.UUID.mostSigBits' on a null object reference
    at java.util.UUID.compareTo(UUID.java:323)
    at com.nbossard.packlist.process.saving.PrefsSavingModule.loadSavedTrip(PrefsSavingModule.java:102)
    at com.nbossard.packlist.process.saving.PrefsSavingModule.updateItem(PrefsSavingModule.java:187)
    at com.nbossard.packlist.gui.MainActivity.updateItem(MainActivity.java:216)
    at com.nbossard.packlist.gui.ItemDetailFragment$1.onClick(ItemDetailFragment.java:73)
    at android.view.View.performClick(View.java:5204)
    at android.view.View$PerformClick.run(View.java:21153)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nbossard** [comment]
This is due to item format change, I added a trip uuid... which is missing on previously saved trips.
Changed code to support this id missing and display a toast

**Comment by nbossard** [comment]
Fixed in branch develop
