### ISSUE TITLE
Crash on v0.8.1 on DatePicker Dialog

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#30]
# User report received from j.p.k.

USER_COMMENT=
REPORT_ID=a3c197de-e9bd-476d-9346-af379c589e2f
APP_VERSION_CODE=12
APP_VERSION_NAME=0.8.1
PACKAGE_NAME=com.nbossard.packlist
FILE_PATH=/data/user/0/com.nbossard.packlist/files
PHONE_MODEL=E5823
ANDROID_VERSION=6.0
BRAND=Sony
PRODUCT=E5823

USER_APP_START_DATE=2016-05-01T13:58:29.216+02:00
USER_CRASH_DATE=2016-05-01T14:00:17.896+02:00
STACK_TRACE=java.lang.IllegalStateException: Fragment already added: DatePickerDialog{8c51ca2 #2 datePickerStart}
at android.support.v4.app.FragmentManagerImpl.addFragment(FragmentManager.java:1323)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:675)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:5514)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nbossard** [comment]
Jorg K sai d : 

> The crash occurred while setting up a new list (adding items).

**Comment by nbossard** [comment]
Closing due to lack of interest and progress
