### ISSUE TITLE
Crash when modifying trip after going to background ( reported by Josh Mudge)

### ISSUE THREAD

**Issue by nbossard** [nbossard/packlist#43]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.nbossard.packlist.gui.TripListFragment.populateList()' on a null object reference
at com.nbossard.packlist.gui.MainActivity.onTripChange(MainActivity.java:266)
at com.nbossard.packlist.process.saving.PrefsSavingModule.updateTrip(PrefsSavingModule.java:352)
at com.nbossard.packlist.process.saving.PrefsSavingModule.addOrUpdateTrip(PrefsSavingModule.java:143)
at com.nbossard.packlist.gui.MainActivity.saveTrip(MainActivity.java:328)
at com.nbossard.packlist.gui.TripDetailFragment.onClickAddItem(TripDetailFragment.java:495)
at com.nbossard.packlist.gui.TripDetailFragment.access$700(TripDetailFragment.java:80)
at com.nbossard.packlist.gui.TripDetailFragment$3.onClick(TripDetailFragment.java:305)
at android.view.View.performClick(View.java:4764)
at android.view.View$PerformClick.run(View.java:19844)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by nbossard** [comment]
android 5.0.1

**Comment by nbossard** [comment]
Steps to reproduce : 
- launch packlist v0.10.2
- open a trip 
- make packlist go to background (press home key)
- wait long enough for system to kill app (or configure in parameter / developer option / don't keep activities)
- return to app (it is in fact restarted)
- modify trip 
  CRASHHHHH
-

**Comment by nbossard** [comment]
Fixed on branch develop, will be in next release
